version: "1.0"

services:
  auth_db:
    image: postgres:15
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_DB: Chatbot_Auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
  chat_db:
    image: postgres:15
    container_name: chat_db
    restart: always
    environment:
      POSTGRES_DB: Chatbot_Chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - chat_db_data:/var/lib/postgresql/data
  auth_service:
    image: ankitrajthakur803/auth_service
    container_name: auth_service
    env_file:
      - .env
    depends_on:
      - auth_db
    ports:
      - "8001:8001"
  chatbot_service:
    image: ankitrajthakur803/chatbot_service
    container_name: chatbot_service
    env_file:
      - .env
    depends_on:
      - chat_db
      - auth_service
    ports:
      - "8002:8002"
volumes:
  auth_db_data:
  chat_db_data:
